#!/usr/bin/env python3
from typing import *



#def solve(n, a, b):
def solve(n: int, a: List[int], b: List[int]) -> List[str]:
    ans = []
    i = 0
    while i < n:
        ans.append(str(a[i] + b[i]))
        i += 1
    return ans
# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n = int(input())
    a = [None for _ in range(n)]
    b = [None for _ in range(n)]
    for i in range(n):
        a[i], b[i] = map(int, input().split())
    ans = solve(n, a, b)
    for i in range(n):
        print(ans[i])

if __name__ == '__main__':
    main()
