#!/usr/bin/env python3
# from typing import *



# def solve(H: int, W: int, A: List[int], B: List[int]) -> Tuple[List[str], str]:
def solve(H, W, A, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W = map(int, input().split())
    A = [None for _ in range(H)]
    B = [None for _ in range(H)]
    for i in range(H):
        A[i], B[i] = map(int, input().split())
    c, d = solve(H, W, A, B)
    for i in range(H):
        print(c[i])
    print(d)

if __name__ == '__main__':
    main()
